AUTH/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import login_or_register, info, logout_view, account_info, edit, code


app_name = 'auth'
urlpatterns = [
    path('', info, name='info'),
    path('edit_profile', edit.as_view(), name='edit_profile'),
    path('code', code.as_view(), name='code'),
    path('auth/', login_or_register.as_view(), name='auth'),
    path('logout/', logout_view, name='logout'),
    path('@<str:account_username>/', account_info, name='account'),
]

chess/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

from .views import api, random_favicon


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('AUTH.urls')),
    path('api/', api.as_view(), name='api'),
    path('', include('game.urls')),
    path('favicon.ico', random_favicon, name='favicon'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.contrib import admin
from django.urls import path, include

from django.shortcuts import redirect

from .views import home, leaders, game, info, hello


app_name = 'chess'
urlpatterns = [
    path('', home, name='home'),
    path('leaders/', leaders, name='leaders'),
    path('games/', lambda request: redirect('chess:home'), name='home_redirect'),
    path('games/<int:game_id>/info/', info, name='info'),
    path('games/<int:game_id>/', game, name='game'),
    path('hello/', hello, name='hello'),
]

game/models.py
from django.db import models
from django.utils import timezone

from AUTH.models import User

from .pieces import *
from copy import deepcopy


def movements_to_str(soft_movements) -> list:
	res = []

	for movement in soft_movements:
		matrix = value_matrix('1', 8, 8)
		for y, line in enumerate(movement):
			for x, piece in enumerate(line):
				if piece:
					matrix[y][x] = str(piece)
				else:
					matrix[y][x] = ''

		res.append(matrix)

	return res

def str_to_movements(movements) -> list:
	res = []

	for movement in movements:
		matrix = value_matrix(None, 8, 8)
		for y, line in enumerate(movement):
			for x, piece in enumerate(line):
				parts = piece.split(' ')
				if len(parts) == 2:
					matrix[y][x] = str_to_piece(piece, pos=[x,y])
				else:
					matrix[y][x] = None

		res.append(matrix)

	return res

def str_to_piece(piece: str, pos=[0,0]) -> Piece:
	parts = piece.split(' ')
	if parts[0] in ['Pawn','Rook','Bishop','Knight','Queen','King'] and parts[1] in ['black','white']:
		return eval(f'{parts[0]}("{parts[1]}", pos={pos})')

def value_matrix(value, x: int, y: int) -> list:
	return [[value for _ in range(x)] for _ in range(y)]

def if_not_ended(func):
	def wrapper(self, *args, **kwargs):
		if self.ended:
			raise ValueError("The game is ended")
		return func(self, *args, **kwargs)
	return wrapper

def if_not_ended_and_started(func):
	def wrapper(self, *args, **kwargs):
		
		if self.ended:
			raise ValueError("The game is ended")
		if not self.playing:
			raise ValueError("The game is not started")

		return func(self, *args, **kwargs)
	return wrapper

def if_time_is_not_up(func):
	def wrapper(self, *args, **kwargs):

		if self.playing:
			timedelta = (timezone.now() - self.last_movement_time).total_seconds()
			if self.color == 'white' and self.white_player_time + timedelta >= self.max_time:
				self.end(win='black', res='time')
			elif self.color == 'black' and self.black_player_time + timedelta >= self.max_time:
				self.end(win='white', res='time')

		return func(self, *args, **kwargs)
	return wrapper


class Game(models.Model):
	start_time = models.DateTimeField(auto_now=True, verbose_name='Start Time')
	end_time = models.DateTimeField(null=True, blank=True, verbose_name='End Time')
	max_time = models.IntegerField(verbose_name='Maximum Time (seconds)', default=15 * 60)
	last_movement_time = models.DateTimeField(auto_now=True, verbose_name='Last Movement Time')
	created_at = models.DateTimeField(auto_now=True, verbose_name='Creation Time')

	white_player = models.ForeignKey(User, on_delete=models.CASCADE, related_name='white_player_games', verbose_name='White Player')
	black_player = models.ForeignKey(User, on_delete=models.CASCADE, related_name='black_player_games', verbose_name='Black Player')
	winner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='winner', verbose_name='Winner')

	white_player_time = models.IntegerField(default=0, verbose_name='White PLayer Time (seconds)')
	black_player_time = models.IntegerField(default=0, verbose_name='White PLayer Time (seconds)  ')

	white_player_score = models.IntegerField(default=0, verbose_name='White PLayer Score')
	black_player_score = models.IntegerField(default=0, verbose_name='White PLayer Score')

	destroyed_pieces = models.JSONField(default=list, verbose_name='Destroyed Pieces')

	movements = models.JSONField(default=movements_to_str([[
		[
			Rook('black', pos=[0,0]), Knight('black', pos=[1,0]), Bishop('black', pos=[2,0]), Queen('black', pos=[3,0]),
			King('black', pos=[4,0]), Bishop('black', pos=[5,0]), Knight('black', pos=[6,0]), Rook('black', pos=[7,0])
		],
		[Pawn('black', pos=[i, 1]) for i in range(8)],
		[None] * 8,
		[None] * 8,
		[None] * 8,
		[None] * 8,
		[Pawn('white', pos=[i, 6]) for i in range(8)],
		[
			Rook('white', pos=[0,7]), Knight('white', pos=[1,7]), Bishop('white', pos=[2,7]), Queen('white', pos=[3,7]),
			King('white', pos=[4,7]), Bishop('white', pos=[5,7]), Knight('white', pos=[6,7]), Rook('white', pos=[7,7])
		],
	]]), verbose_name='movements')
	playing = models.BooleanField(default=False)
	ended = models.BooleanField(default=False)
	end_reason = models.CharField(null=True, max_length=50)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.actions = [self.move, self.castling, self.transform_pawn]

	@if_time_is_not_up
	def move(self, _from: list, _to: list, predict_score: bool = False, start_score: int = 100):
		last_movement = self.soft_movements[-1]
		first_movement = False

		if isinstance(last_movement[_from[1]][_from[0]], Piece):
			if self.movement_count == 0 and last_movement[_from[1]][_from[0]].color == self.color == 'white':
				first_movement = True
			elif last_movement[_from[1]][_from[0]].color != self.color: # everything has its time
				raise ValueError(f"{len(self.movements)} movement is for {self.color}, but piece at {_from} is a {last_movement[_from[1]][_from[0]].color}")
		else:
			raise ValueError("Position from at last game move is empty or not on board, there must be piece to move it")

		save_king_movements = self.get_save_king_movements(self.color)
		if len(save_king_movements) == 0:
			self.end(win='black' if self.color == 'white' else 'white', res='checkmate')

		for i, fromto in enumerate([_from, _to]):
			if isinstance(fromto, list):
				if len(fromto) == 2:
					if isinstance(fromto[0], int) and isinstance(fromto[1], int):
						if 0 <= fromto[0] <= 7 and 0 <= fromto[1] <= 7:
							continue

			raise ValueError(f"Position {['from', 'to'][i]} is invalid: {fromto}")
		
		if self.ended:
			raise ValueError("The game is ended")
		if not self.playing and not first_movement:
			raise ValueError("The game is not started")

		destroyed_piece = last_movement[_to[1]][_to[0]] if isinstance(last_movement[_to[1]][_to[0]], Piece) else None

		new_movement = self.make_movement(last_movement, _from, _to, reg_destroyed_pieces=True)
		if (list(_from), list(_to)) in save_king_movements or not (tuple(_from), tuple(_to)) in all_movements:
			if not predict_score:
				if first_movement:
					self.start()
				self.set_scores(new_movement, self.color, start_score, destroyed_piece, transformed_pawn=False)
				self.save_movement(new_movement)
			else:
				return self.get_movement_score(new_movement, self.color, start_score, destroyed_piece, transformed_pawn=False)
		else:
			formatted_save_movements = '\n'.join([
				f'{i+1}. [{movement[0]} -> {movement[1]}]' for i, movement in enumerate(save_king_movements)
			])
			raise ValueError(f"Your king is in danger! You must safe king. To do it, you have this movements:\n{formatted_save_movements}")

	@if_time_is_not_up
	def transform_pawn(self, pos_or_pawn, to: Piece, predict_score: bool = False, start_score: int = 100):
		if isinstance(pos_or_pawn, (list, tuple)):
			if len(pos_or_pawn) == 2:
				if isinstance(self[pawn_pos], Pawn):
					obj = self[pawn_pos]
				else:
					raise ValueError(f'Not Pawn at position {pos_or_pawn}')
			else:
				raise ValueError(f'Invalid position {pos_or_pawn}. Position must be list/tuple with 2 integer values')

		if isinstance(pos_or_pawn, Pawn):
			if self[pos_or_pawn.pos] == Pawn:
				obj = pos_or_pawn
			else:
				raise ValueError(f'Argument {pos_or_pawn} with pos {pos_or_pawn.pos} is not in this game. It must be at last movement ( game.soft_movements[-1] to get it )')
		else:
			raise ValueError(f'Invalid argument {pos_or_pawn}. It must be position (list/tuple with 2 integer values) or Pawn object')

		if isinstance(to, Piece) and not isinstance(to, (Pawn, King)):
			last_movement = self.soft_movements[-1]
			if self.color == obj.color: # everything has its time
				if obj.color == 'white' and obj.pos[1] in [0, 1]:

					if self.ended:
						raise ValueError("The game is ended")
					if not self.playing:
						raise ValueError("The game is not started")

					last_movement[obj.x][0] = to(obj.color, pos=[obj.x][0])
					if not predict_score:
						if len(self.get_save_king_movements(self.color)) == 0:
							self.end(win='black' if self.color == 'white' else 'white', res='checkmate')
						self.set_scores(last_movement, self.color, start_score, [], transformed_pawn=True)
						self.save_movement(last_movement)
					else:
						return self.get_movement_score(last_movement, self.color, start_score, [], transformed_pawn=True)

				elif obj.color == 'black' and obj.pos[1] in [6, 7]:

					last_movement[obj.x][7] = to(obj.color, pos=[obj.x][7])
					if not predict_score:
						self.set_scores(last_movement, self.color, start_score, [], transformed_pawn=True)
						self.save_movement(last_movement)
					else:
						return self.get_movement_score(last_movement, self.color, start_score, [], transformed_pawn=True)

				else:
					raise ValueError(f'{str(obj)} at {obj.pos} can not be transformated')
			else:
				raise ValueError(f"{len(self.movements)} movement is for {self.color}, but this Pawn is a {obj.color}")
		else:
			raise ValueError(f'Invalid argument {to}. It must be Piece object ( not Pawn )')

	@if_not_ended_and_started
	@if_time_is_not_up
	def give_up(self, color: str, return_json: bool = False):
		self.end(win=color, res='gived_up')

	@if_not_ended
	@if_time_is_not_up
	def castling(self, color: str, side: str, predict_score: bool = False, start_score: int = 100):
		if side in ['left', 'right']: # 1 - left, 0 - right
			side = 1 if side == 'left' else 0
			side = not side if self.color == 'black' else side
		else:
			raise ValueError(f'Invalid argument {side}. It must be "left"/"right" ( if it is for black player it will be mirrored )')

		if color == self.color: # everything has its time
			if self.ended:
				raise ValueError("The game is ended")
			if not self.playing:
				raise ValueError("The game is not started")

			kings = [ piece for piece in self.alive_pieces if isinstance(piece, King) ]
			king = [ king for king in kings if king.color == color ][0]

game/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.conf import settings
from django.urls import reverse

from AUTH.models import User
from game.models import Game
import requests as rq, json


def home(request):
	return render(request, 'home.html', {'user': request.user})
def hello(request):
    return render(request, 'hello.html', {'user': request.user})

def leaders(request):
	leaders_url = request.build_absolute_uri(f'{reverse("api")}?key=leaders&portion={settings.LEADERS_PORTION}&index=0')
	first_portion = json.loads(rq.get(leaders_url).content)
	return render(request, 'leaders.html', {
		'user': request.user,
		'users': [ User.objects.get(username=user['username']) for user in first_portion ],
		'leaders_url': leaders_url[:-1]
	})

def game(request, game_id: int):
	game = get_object_or_404(Game, id=game_id)
	if request.user in game.players:
		try:
			return render(request, 'game.html', {
				'user': request.user,
				'game': game,
				'white_player_time': int(game.passed_time('white')),
				'black_player_time': int(game.passed_time('black')),
				'max_time': game.max_time
			})
		except ValueError as ve:
			if str(ve) == 'The game is ended':
				return info(request, game_id)
			else:
				raise ValueError(ve)
	else:
		return redirect('chess:info', game.id)

def info(request, game_id: int):
	game = get_object_or_404(Game, id=game_id)
	return render(request, 'game_info.html', {'user': request.user, 'game': game, 'white': game.white_player, 'black': game.black_player, 'max_time': game.max_time/60})

game/templates/game_info.html
{% extends 'base.html' %}

{% block title %}Игра {{ white.username }} VS {{ black.username }}{% endblock %}

{% block content %}

<style>
    .board-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        overflow: hidden;
    }

    .board {
        display: grid;
        grid-template-columns: repeat(8, 1fr);
        grid-template-rows: repeat(8, 1fr);
        margin: 0 20px;
        width: 80vmin;
        height: 80vmin;
    }

    .cell {
        background-color: #FFF;
        transition: background-color 0.15s;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .cell.black {
        background-color: #888;
    }

    .cell.highlight {
        background-color: #FFD700 !important;
    }

    .cell.available {
        background-color: #32CD32 !important;
    }

    .piece {
        width: 95%;
        height: 95%;
        background-size: contain;
        background-repeat: no-repeat;
        background-position: center;
    }
</style>


Краткая инфа о игре:
    Белый
    <img src="{{ white.avatar.url }}" alt="Аватар {{ white.username }}" class="big-user-avatar">
    {% if white.first_name != '' and white.last_name != '' %}
        {{ white.first_name }} {{ white.last_name }}
    {% elif white.first_name != '' and white.last_name == '' %}
        {{ white.first_name }}
    {% else %}
        @{{ white.username }}
    {% endif %}
    <p>Счет: <span id="white_score">...</span></p>
    <p>Время: <span id="white_passed_time">...</span> / {{ game.max_time }}</p>
    <p>Потеряно фигур: <span id="destroyed_white_pieces">...</span></p>

    Черный
    <img src="{{ black.avatar.url }}" alt="Аватар {{ black.username }}" class="big-user-avatar">
    {% if black.first_name != '' and black.last_name != '' %}
        {{ black.first_name }} {{ black.last_name }}
    {% elif black.first_name != '' and black.last_name == '' %}
        {{ black.first_name }}
    {% else %}
        @{{ black.username }}
    {% endif %}
    <p>Счет: <span id="black_score">...</span></p>
    <p>Время: <span id="black_passed_time">...</span> / {{ game.max_time }}</p>
    <p>Потеряно фигур: <span id="destroyed_black_pieces">...</span></p>

<div class="game-summary">
    <p id="winner">...</p>
    <p>Последний ход был: <span id="last_movement_time">...</span></p>
    <p>Начало игры: {{ game.start_time }}</p>
    <p>Статус: <span id="game_status">...</span></p>
</div>

<div class="board-container">
    <div class="board" id="board"></div>
</div>

<script>
    const fetch_timer = 3000
    const color = 'white'
    const mirrored = true


    const fetchData = () => {
        fetch(`/api/?key=game&id={{ game.id }}`)
            .then(response => response.json())
            .then(data => {
                document.getElementById('white_score').textContent = data.white_score
                document.getElementById('white_passed_time').textContent = data.white_passed_time
                document.getElementById('destroyed_white_pieces').textContent = data.destroyed_white_pieces

                document.getElementById('black_score').textContent = data.black_score
                document.getElementById('black_passed_time').textContent = data.black_passed_time
                document.getElementById('destroyed_black_pieces').textContent = data.destroyed_black_pieces

                if (data.winner) {
                    document.getElementById('winner').textContent = `Победил: ${data.winner}`
                } else {
                    document.getElementById('winner').textContent = 'Победитель пока не определен'
                }

                switch (data.status) {
                    case 0:
                        document.getElementById('game_status').textContent = 'Игра окончена'
                        break
                    case 1:
                        document.getElementById('game_status').textContent = 'Игра приостановлена или не началась'
                        break
                    case 2:
                        document.getElementById('game_status').textContent = 'Игра продолжается'
                        break
                }

                document.getElementById('last_movement_time').textContent = data.last_movement_time

                updatePieces(data.board)
            })
            .catch(error => console.error('Error fetching data:', error));
    }

    const createBoard = () => {
        const board = document.getElementById('board')
        for (let y = 0; y < 8; y++) {
            for (let x = 0; x < 8; x++) {
                const cell = document.createElement('div')
                cell.className = 'cell'
                if (color === 'white') {
                    if ((x + y) % 2 === 0) {
                        cell.className += ' black'
                    }
                } else {
                    if ((x + y) % 2 !== 0) {
                        cell.className += ' black'
                    }
                }
                cell.dataset.x = x
                cell.dataset.y = y
                board.appendChild(cell)
            }
        }
    }

    const updatePieces = (boardLayout) => {
        const cells = document.querySelectorAll('.cell')
        for (let x = 0; x < 8; x++) {
            for (let y = 0; y < 8; y++) {
                const pieceName = boardLayout[x][y].toLowerCase()
                const cell = cells[(mirrored ? 7 - x : x) * 8 + y]

                if (pieceName) {
                    if (cell.children.length === 0 || cell.children[0].dataset.pieceName !== pieceName) {
                        if (cell.children.length > 0) {
                            cell.removeChild(cell.children[0]);
                        }
                        const piece = document.createElement('div')
                        piece.className = 'piece'
                        piece.style.backgroundImage = `url("/media/modified_pieces/${pieceName.split(' ')[1]}_${pieceName.split(' ')[0]}.png")`
                        piece.dataset.color = pieceName.split(' ')[1]
                        piece.dataset.type = pieceName.split(' ')[0]
                        piece.dataset.pieceName = pieceName
                        cell.appendChild(piece)
                    }
                } else {
                    if (cell.children.length > 0) {
                        cell.removeChild(cell.children[0])
                    }
                }
            }
        }
    }


    setInterval(fetchData, fetch_timer)

    createBoard()
    fetchData()
</script>

{% endblock %}

game/templates/hello.html
{% extends 'base.html' %}

{% block title %}Зарегестрируйся для получения таких возможностей{% endblock %}

{% block content %}
    test
{% endblock %}

game/templates/home.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block header %}
    <style>
        .container {
            display: flex;
            justify-content: space-between;
        }
        .column {
            width: 48%;
        }
        h3 {
            margin-top: 0;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="column">
            <h3>Список игр</h3>
            <ul id="games-list"></ul>
        </div>
        <div class="column">
            <h3>Список пользователей</h3>
            <ul id="users-list"></ul>
        </div>
    </div>

    <script>
        let activeGamesIndex = 0
        let usersQueueIndex = 0
        const portion = 2

        const loadMoreData = () => {
            fetch(`/api/?key=active_games&index=${activeGamesIndex}&portion=${portion}`)
                .then(response => response.json())
                .then(data => {
                    const gamesList = document.getElementById('games-list')
                    data.forEach(game => {
                        const gameElement = document.createElement('li')
                        gameElement.innerHTML = `<a href="{% url 'chess:home_redirect' %}${game[0]}/info">Game ${game[2]} vs ${game[3]}</a>`
                        gamesList.appendChild(gameElement)
                    })
                    activeGamesIndex += portion
                })

            fetch(`/api/?key=users_queue&index=${usersQueueIndex}&portion=${portion}`)
                .then(response => response.json())
                .then(data => {
                    const usersList = document.getElementById('users-list')
                    data.forEach(user => {
                        const userElement = document.createElement('li')
                        userElement.innerHTML = `<a href="#" onclick="letsPlay('${user[0]}')">User: ${user[0]}</a>`
                        usersList.appendChild(userElement)
                    })
                    usersQueueIndex += portion
                })
        }

        const letsPlay = (username) => {
            fetch(`/api/lets_play?username=${username}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                body: JSON.stringify({ username: username })
            }).then(response => {
                if (response.ok) {
                    alert('Game request sent successfully!')
                }
            })
        }

        const getCookie = (name) => {
            let cookieValue = null
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split('')
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim()
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1))
                        break
                    }
                }
            }
            return cookieValue
        }

        window.onscroll = () => {
            if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
                loadMoreData()
            }
        }

        document.addEventListener('DOMContentLoaded', loadMoreData)
    </script>
{% endblock %}

game/templates/leaders.html
{% extends 'base.html' %}

{% block title %}Топ игроков{% endblock %}

{% block header %}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    th {
        background-color: #f2f2f2;
    }
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>
{% endblock %}

{% block content %}

<table>
    <thead>
        <tr>
            <th>Ник</th>
            <th>Счет</th>
            <th>Уровень</th>
            <th>Количество игр</th>
            <th>Винрейт</th>
        </tr>
    </thead>
    <tbody>
    {% for iuser in users %}
        <tr>
            <td>
                {% if iuser.first_name != '' and iuser.last_name != '' %}
                    {{ iuser.first_name }} {{ iuser.last_name }}
                {% elif iuser.first_name != '' and iuser.last_name == '' %}
                    {{ iuser.first_name }}
                {% else %}
                    @{{ iuser.username }}
                {% endif %}
            </td>
            <td>{{ iuser.global_score }}</td>
            <td>{{ iuser.level }}</td>
            <td>{{ iuser.games_count }}</td>
            <td>{{ iuser.winrate }}%</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<!-- Динамически подгружать таблицу порциями запросом к api/?key=leaders&portion=int&index=int -->
<!-- Ответ от апи содаржит json список словарей с ключами username, global_score, level, games_count, winrate -->

{% endblock %}