AUTH/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import login_or_register, info, logout_view, account_info, edit, code


app_name = 'auth'
urlpatterns = [
    path('', info, name='info'),
    path('edit_profile', edit.as_view(), name='edit_profile'),
    path('code', code.as_view(), name='code'),
    path('auth/', login_or_register.as_view(), name='auth'),
    path('logout/', logout_view, name='logout'),
    path('@<str:account_username>/', account_info, name='account'),
]

chess/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

from .views import api, random_favicon


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('AUTH.urls')),
    path('api/', api.as_view(), name='api'),
    path('', include('game.urls')),
    path('favicon.ico', random_favicon, name='favicon'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/urls.py
from django.contrib import admin
from django.urls import path, include

from django.shortcuts import redirect

from .views import home, leaders, game, info, hello


app_name = 'chess'
urlpatterns = [
    path('', home, name='home'),
    path('leaders/', leaders, name='leaders'),
    path('games/', lambda request: redirect('chess:home'), name='home_redirect'),
    path('games/<int:game_id>/info/', info, name='info'),
    path('games/<int:game_id>/', game, name='game'),
    path('hello/', hello, name='hello'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <title>{% block title %}Site{% endblock %}</title>
    <style>
        .profile-button {
            display: flex;
            align-items: center;
            color: #ffffff;
            text-decoration: none;
        }

        .profile-button img {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            margin-right: 10px;
        }

        #timer-menu {
            display: none;
        }

        main {
            padding: 20px;
        }
    </style>
    {% block header %}{% endblock %}
</head>
<body class="dark-theme">
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'chess:home' %}">Главная</a></li>
                <li><a href="{% url 'chess:leaders' %}">Список лидеров</a></li>
                {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}">Админка</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'auth:info' %}" class="profile-button">
                            <img src="{{ user.avatar.url }}" alt="Твой аватар">
                            <span>{{ user.username }}</span>
                        </a>
                    </li>
                    <li><a href="{% url 'auth:logout' %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url 'auth:auth' %}">Регистрация/Вход</a></li>
                {% endif %}
            </ul>
            
            {% if user.is_authenticated %}
                {% if user.is_in_game %}
                    <button id="continue-game-button" onclick="continue_game()">Продолжить игру</button>
                {% else %}
                    <button id="start-game-button" onclick="start_game()">Начать игру</button>
                    <form id="time-range-form">
                        <label for="min-time">Минимум минут на игру:</label>
                        <input type="number" id="min-time" name="min-time" min="1" max="60" value="1">
                        <br>
                        <label for="max-time">Максимум минут на игру:</label>
                        <input type="number" id="max-time" name="max-time" min="1" max="60" value="10">
                    </form>
                    <div id="timer-menu">
                        <p>Таймер: <span id="search-timer">0:00</span></p>

                        <p>Людей в очереди: <span id="queue-count">0</span></p>
                        Средняя статистика игроков:
                        <p>Сыграно матчей: <span id="games-count">0</span></p>
                        <p>Винрейт: <span id="winrate">0.0</span></p>
                        <p>Уровень: <span id="level">0</span></p>
                        <p>Счет: <span id="score">0</span></p>
                    </div>
                {% endif %}
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <script>
        {% if not user.is_in_game %}
            let ws
            let search_timerInterval
            let search_seconds
            let wait_seconds
            let wait_timerInterval

            const max_wait_time = 15

            const start_button = document.querySelector("#start-game-button")
            const timerElement = document.getElementById("timer-menu")
            const search_timerSpan = document.getElementById("search-timer")
            const queue_count_info = document.getElementById('queue-count')
            const games_count_info = document.getElementById('games-count')
            const winrate_info = document.getElementById('winrate')
            const level_info = document.getElementById('level')
            const score_info = document.getElementById('score')

            const form = document.getElementById("time-range-form")
            const minTimeInput = document.getElementById("min-time")
            const maxTimeInput = document.getElementById("max-time")


            const get_game_url = (game_id) => {
                return `/games/${game_id}`
            }

            const validateTimeRange = () => {
                let minValue = minTimeInput.value
                let maxValue = maxTimeInput.value

                while (minValue[0] == '0') {
                    minValue = minValue.slice(1, minValue.length)
                    minTimeInput.value = minValue
                }
                while (maxValue[0] == '0') {
                    maxValue = maxValue.slice(1, maxValue.length)
                    maxTimeInput.value = maxValue
                }

                let minTime = parseInt(minValue)
                let maxTime = parseInt(maxValue)

                if (maxTime > 60) {
                    maxTimeInput.value = 60
                } else if (maxTime < 0) {
                    maxTimeInput.value = 0
                }
                if (minTime < 0) {
                    minTimeInput.value = 0
                } else if (minTime > 59) {
                    minTimeInput.value = 59
                }
                if (minTime >= maxTime) {
                    minTimeInput.value = maxTime - 1
                }
            }

            {% if user.is_in_game and user.is_authenticated %}
                minTimeInput.addEventListener('change', validateTimeRange)
                maxTimeInput.addEventListener('change', validateTimeRange)
            {% endif %}

            const getSafeValue = (value, def = '') => {
                return value != undefined ? value : def;
            }

            const start_game = () => {
                ws = new WebSocket('ws://' + window.location.host + '/ws/queue/')

                ws.onopen = function(event) {
                    console.log('WebSocket is open now.')
                    ws.send(JSON.stringify({
                        'type': 'time_form',
                        'min': form["min-time"].value,
                        'max': form["max-time"].value
                    }))
                }

                ws.onmessage = function(event) {
                    console.log('message is received')
                    const data = JSON.parse(event.data)

                    switch (data.type) {
                        case 'queue_players_info':
                            queue_count_info.textContent = getSafeValue(data.count, queue_count_info.textContent)
                            games_count_info.textContent = getSafeValue(data.games, games_count_info.textContent)
                            level_info.textContent = getSafeValue(data.level, level_info.textContent)
                            score_info.textContent = getSafeValue(data.score, score_info.textContent)
                            winrate_info.textContent = getSafeValue(data.winrate, winrate_info.textContent)
                            break
                        case 'game_found':
                            console.log('game is found')
                            const time = getSafeValue(data.max_time, 'Неизвестно')
                            const formattedTime = typeof time === 'number' ? `${time} минут (${time * 60} секунд)` : time
                            stop_timer()

                            Swal.fire({
                                title: 'Подтвердите готовность',
                                html: `
                                <div style="user-select: none">
                                    <p>Осталось <span id="wait-timer">${max_wait_time}</span> секунд</p>
                                    <p>Время игры: ${formattedTime}</p>
                                    <p>Ваш соперник:</p>
                                    ${getSafeValue(data.opponent.avatar) ? `<img src="${data.opponent.avatar}" alt="Аватарка соперника" width="100" height="100">` : ''}
                                    <p id="opponent-readiness">Не готов</p>
                                    <p>Имя: ${getSafeValue(data.opponent.name, 'Неизвестно')}</p>
                                    <p>Уровень: ${getSafeValue(data.opponent.level, 'Неизвестно')}</p>
                                    <p>Winrate: ${data.opponent.winrate != undefined ? data.opponent.winrate + '%' : 'Неизвестно'}</p>
                                </div>
                                `,
                                showCancelButton: true,
                                confirmButtonText: 'Играть',
                                cancelButtonText: 'Отменить',
                                preConfirm: () => {
                                    return false
                                },
                                willOpen: () => {
                                    const confirmButton = Swal.getConfirmButton()
                                    confirmButton.addEventListener('click', () => {
                                        ws.send(JSON.stringify({ 'type': 'i_am_ready' }))
                                        confirmButton.disabled = true
                                        confirmButton.style.backgroundColor = 'gray'
                                    })
                                }
                            }).then((result) => {
                                if (!result.isConfirmed) {
                                    ws.send(JSON.stringify( {'type': 'cancel_game'} ))
                                    console.log('game is canceled')
                                    start_timer(search_seconds)
                                }
                                clearInterval(wait_timerInterval)
                                wait_seconds = 0
                            })
                            wait_seconds = max_wait_time
                            wait_timerInterval = setInterval(() => {
                                const wait_timerSpan = document.getElementById("wait-timer")

                                wait_seconds--
                                wait_timerSpan.textContent = wait_seconds

                                if (wait_seconds <= 0) {
                                    console.log('game is canceled')
                                    Swal.close()
                                    start_timer(search_seconds)
                                    wait_seconds = 0
                                    ws.close()
                                }
                            }, 1000)
                            break

                        case 'game_is_canceled':
                            console.log('game is canceled')
                            Swal.close()
                            start_timer(search_seconds)
                            break

                        case 'opponent_is_ready':
                            console.log('opponent is ready')
                            const readness = document.getElementById("opponent-readiness")
                            readness.textContent = 'Готов'
                            break

                        case 'game_info':
                            console.log('game is ready')
                            window.location.href = get_game_url(data.game_id)
                            break
                    }
                }

                ws.onclose = function(event) {
                    console.log('WebSocket is closed now.')
                    stop_game()
                }

                start_button.textContent = "Прервать поиск"
                start_button.onclick = stop_game

                timerElement.style.display = "block"
                start_timer()
            }

            const stop_game = () => {
                start_button.textContent = "Начать игру"
                start_button.onclick = start_game
                if (ws != null) {
                    ws.close()
                }
                timerElement.style.display = "none"
                search_timerSpan.textContent = "0"
                stop_timer()
            }

            const start_timer = (sec = 0) => {
                search_seconds = sec
                if (search_timerInterval != null) {
                    clearInterval(search_timerInterval)
                }
                search_timerInterval = setInterval(() => {
                    search_seconds++
                    const mins = Math.floor(search_seconds / 60)
                    const secs = search_seconds % 60
                    search_timerSpan.textContent = `${mins}:${secs < 10 ? `0${secs}` : secs}`
                }, 1000)
            }
            const stop_timer = () => {
                clearInterval(search_timerInterval)
            }
        {% else %}
            const continue_game = () => {
                window.location.href =  '/games/{{ user.active_game.id }}'
            }
        {% endif %}
    </script>
</body>
</html>